apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cnfconfigurations.pantheon.tech
spec:
  group: pantheon.tech
  names:
    kind: CNFConfiguration
    listKind: CNFConfigurationList
    plural: cnfconfigurations
    singular: cnfconfiguration
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                microservice:
                  type: string
                configItems:
                  type: array
                  items:
                    type: object
                    properties:
                      module:
                        type: string
                      version:
                        type: string
                      type:
                        type: string
                      data:
                        type: string
