---
# This cluster role defines a set of permissions required for cnf-crd.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cnf-crd
  namespace: default
rules:
  - apiGroups:
      - apiextensions.k8s.io
      - pantheon.tech
    resources:
      - customresourcedefinitions
      - cnfconfigurations
    verbs:
      - "*"

---
# This defines a service account for cnf-crd.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cnf-crd
  namespace: default

---
# This binds the cnf-crd cluster role with cnf-crd service account.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cnf-crd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cnf-crd
subjects:
  - kind: ServiceAccount
    name: cnf-crd
    namespace: default

---
apiVersion: v1
kind: Pod
metadata:
  name: cnf-crd
  namespace: default
  labels:
    app: cnf-crd
spec:
  serviceAccountName: cnf-crd
  initContainers:
    # This init container waits until etcd is started
    - name: wait-foretcd
      image: busybox:1.29.3
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh"]
      args:
        - -c
        - |
          until nc -w 2 cnf-etcd.default.svc.cluster.local 12379; do 
            echo "Waiting for ETCD to start..."; 
            sleep 2; 
          done;
  containers:
    - name: cnf-crd
      image: pantheontech/cnf-crd:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: ETCD_CONFIG
          value: "/etc/etcd/etcd.conf"
      volumeMounts:
        - name: etcd-cfg
          mountPath: /etc/etcd
  volumes:
    - name: etcd-cfg
      configMap:
        name: cnf-etcd-cfg

---
# etcd config used by CNFs deployed in the host network namespace
apiVersion: v1
kind: ConfigMap
metadata:
  name: cnf-etcd-cfg-for-nodeport
data:
  etcd.conf: |
    dial-timeout: 10000000000
    allow-delayed-start: true
    insecure-transport: true
    endpoints:
      - "cnf-etcd.default.svc.cluster.local:12379"

---
# etcd config used by CNF with their own network namespace
apiVersion: v1
kind: ConfigMap
metadata:
  name: cnf-etcd-cfg
data:
  etcd.conf: |
    dial-timeout: 10000000000
    allow-delayed-start: true
    insecure-transport: true
    endpoints:
      - "cnf-etcd.default.svc.cluster.local:12379"

---
apiVersion: v1
kind: Service
metadata:
  name: cnf-etcd
spec:
  type: ClusterIP
  selector:
    app: cnf-etcd
  ports:
    - port: 12379
      targetPort: 12379
      protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: cnf-etcd
  labels:
    app: cnf-etcd
spec:
  containers:
    - name: cnf-etcd
      image: quay.io/coreos/etcd:v3.6.0-rc.2
      imagePullPolicy: IfNotPresent
      env:
        - name: ETCDCTL_API
          value: "3"
      command:
        - /usr/local/bin/etcd
      args:
        - --name=cnf-etcd
        - --data-dir=/var/cnf-etcd/data
        - --advertise-client-urls=http://0.0.0.0:12379
        - --listen-client-urls=http://0.0.0.0:12379
        - --listen-peer-urls=http://0.0.0.0:12380
