apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nsm-resource-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: nsm-resource-daemonset
  template:
    metadata:
      labels:
        name: nsm-resource-daemonset
    spec:
      hostPID: true
      hostNetwork: true
      serviceAccountName: nsm-resource-manager  # Ensure RBAC permissions
      containers:
      - name: nsm-resource-container
        image: curlimages/curl:latest  # Use an image that includes `curl`
        command: ["/bin/sh", "-c"]
        args:
          - |
            while true; do
              curl -X PATCH -H "Content-Type: application/json" --data '{
                "status": {
                  "capacity": {
                    "networkservicemesh.io/socket": "10"
                  },
                  "allocatable": {
                    "networkservicemesh.io/socket": "10"
                  }
                }
              }' --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
              -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
              https://kubernetes.default.svc/api/v1/nodes/$(hostname)/status;
              sleep 60;
            done;
        securityContext:
          privileged: true
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
